format = """
[î‚¶](#9A348E)\
$username\
$gcloud\
$aws\
[î‚°](bg:#DA627D fg:#9A348E)\
$directory\
[î‚°](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[î‚°](fg:#FCA17D bg:#86BBD8)\
$golang\
$nodejs\
$php\
$python\
$ruby\
$rust\
[î‚°](fg:#86BBD8 bg:#06969A)\
$docker_context\
$package\
[î‚°](fg:#06969A bg:#33658A)\
$battery\
$env_var\
$cmd_duration\
$sudo\
[î‚° ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
add_newline=false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
# show_always = true
disabled=true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
truncate_to_repo=false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[battery]
discharging_symbol="ğŸ’€ "
charging_symbol = "ğŸ”‹ "

[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]] # "bold yellow" style and ğŸ’¦ symbol when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[docker_context]
# symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
# ignore_branches = ["master", "main"]
always_show_remote=true
format = '[ $symbol $branch(:\($remote_branch\)) ]($style)'
style = "bg:#FCA17D fg:#9A348E"
symbol = "ğŸŒ± "

[git_status]
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
conflicted = "ğŸ³"
deleted = "ğŸ—‘"
diverged = "ğŸ˜µ"
format = '[$all_status$ahead_behind ]($style)'
modified = "ğŸ“"
renamed = "ğŸ‘…"
staged = '[++\($count\)](green)'
stashed = "ğŸ“¦"
style = "bg:#FCA17D"
untracked = "ğŸ¤·"
up_to_date = "âœ“"

[golang]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[php]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[ruby]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
min_time = 100
style = "bg:#33658A"
format = '[ $duration ]($style)'
min_time_to_notify=10000
show_notifications=true

# [env_var.SHELL]
# variable = "SHELL"
# default = "unknown shell"

# [env_var.USER]
# default = "unknown user"

[gcloud]
style = "bg:#9A348E"
format = '[ğŸ”¹($profile )(\($region\) )(\[$duration\] )]($style)'

[aws]
style = "bg:#9A348E"
format = '[ğŸ”¸($profile )(\($region\) )(\[$duration\] )]($style)'

[aws.region_aliases]
us-east-1='ue1'

[package]
style = "bg:#06969A"

[sudo]
style = "bg:#33658A"
disabled=false
format=	"[ as $symbol]($style)"
